local M = {}

M.highlights_base = function(colors)
  return {
    Normal                 = { fg = colors.foreground, bg = colors.background },
    StatusLineNC           = { bg = colors.background, fg = colors.color1 },
    StatusLine             = { bg = colors.background, fg = colors.background },
    SignColumn             = { bg = colors.background, fg = colors.background },
    MsgArea                = { fg = colors.foreground, bg = colors.background },
    ModeMsg                = { fg = colors.foreground, bg = colors.background },
    MsgSeparator           = { fg = colors.foreground, bg = colors.background },
    SpellBad               = { fg = colors.color2 },
    SpellCap               = { fg = colors.color6 },
    SpellLocal             = { fg = colors.color4 },
    SpellRare              = { fg = colors.color6 },
    NormalNC               = { fg = colors.foreground, bg = colors.background },
    Pmenu                  = { fg = colors.foreground, bg = colors.background },
    PmenuSel               = { fg = colors.background, bg = colors.color4 },
    WildMenu               = { fg = colors.color7, bg = colors.color4 },
    CursorLineNr           = { fg = colors.color1 },
    Comment                = { fg = colors.color3 },
    Folded                 = { fg = colors.color4, bg = colors.background },
    FoldColumn             = { fg = colors.color4, bg = colors.background },
    LineNr                 = { fg = colors.color9, bg = colors.background },
    FloatBorder            = { fg = colors.foreground, bg = colors.background },
    Whitespace             = { fg = colors.color1 },
    VertSplit              = { fg = colors.background, bg = colors.color1 },
    CursorLine             = { bg = colors.background },
    CursorColumn           = { bg = colors.background },
    ColorColumn            = { bg = colors.background },
    NormalFloat            = { bg = colors.background },
    Visual                 = { bg = colors.color1, fg = colors.foreground },
    VisualNOS              = { bg = colors.background },
    WarningMsg             = { fg = colors.color3, bg = colors.background },
    DiffAdd                = { fg = colors.background, bg = colors.color4 },
    DiffChange             = { fg = colors.background, bg = colors.color5 },
    DiffDelete             = { fg = colors.background, bg = colors.color11 },
    QuickFixLine           = { bg = colors.color2 },
    PmenuSbar              = { bg = colors.background },
    PmenuThumb             = { bg = colors.color2 },
    MatchParen             = { fg = colors.color4, bg = colors.background },
    Cursor                 = { fg = colors.foreground, bg = colors.cursor },
    lCursor                = { fg = colors.foreground, bg = colors.cursor },
    CursorIM               = { fg = colors.foreground, bg = colors.cursor },
    TermCursor             = { fg = colors.foreground, bg = colors.cursor },
    TermCursorNC           = { fg = colors.foreground, bg = colors.cursor },
    Conceal                = { fg = colors.color4, bg = colors.background },
    Directory              = { fg = colors.color4 },
    SpecialKey             = { fg = colors.color4 },
    Title                  = { fg = colors.color4 },
    ErrorMsg               = { fg = colors.color11, bg = colors.background },
    Search                 = { fg = colors.foreground, bg = colors.color1 },
    IncSearch              = { fg = colors.foreground, bg = colors.color1 },
    Substitute             = { fg = colors.color1, bg = colors.color6 },
    MoreMsg                = { fg = colors.color5 },
    Question               = { fg = colors.color5 },
    EndOfBuffer            = { fg = colors.background },
    NonText                = { fg = colors.color1 },
    Variable               = { fg = colors.color5 },
    String                 = { fg = colors.color11 },
    Character              = { fg = colors.color12 },
    Constant               = { fg = colors.color9 },
    Number                 = { fg = colors.color9 },
    Boolean                = { fg = colors.color9 },
    Float                  = { fg = colors.color9 },
    Identifier             = { fg = colors.color8 },
    Function               = { fg = colors.color13 },
    Operator               = { fg = colors.color5 },
    Type                   = { fg = colors.color10 },
    StorageClass           = { fg = colors.color10 },
    Structure              = { fg = colors.color14 },
    Typedef                = { fg = colors.color10 },
    Keyword                = { fg = colors.color14 },
    Statement              = { fg = colors.color8 },
    Conditional            = { fg = colors.color14 },
    Repeat                 = { fg = colors.color10 },
    Label                  = { fg = colors.color10 },
    Exception              = { fg = colors.color6 },
    Include                = { fg = colors.color6 },
    PreProc                = { fg = colors.color10 },
    Define                 = { fg = colors.color14 },
    Macro                  = { fg = colors.color6 },
    PreCondit              = { fg = colors.color6 },
    Special                = { fg = colors.color12 },
    SpecialChar            = { fg = colors.color15 },
    Tag                    = { fg = colors.color10 },
    Debug                  = { fg = colors.color11 },
    Delimiter              = { fg = colors.color15 },
    SpecialComment         = { fg = colors.color2 },
    Ignore                 = { fg = colors.color7, bg = colors.background },
    Todo                   = { fg = colors.color10, bg = colors.background },
    Error                  = { fg = colors.color11, bg = colors.background },
    TabLine                = { fg = colors.color2, bg = colors.background },
    TabLineSel             = { fg = colors.foreground, bg = colors.background },
    TabLineFill            = { fg = colors.foreground, bg = colors.background },
    CmpDocumentationBorder = { fg = colors.color5, bg = colors.background },
    CmpDocumentation       = { fg = colors.color5, bg = colors.background },
    CmpItemAbbr            = { fg = colors.foreground, bg = colors.background },
    CmpItemAbbrDeprecated  = { fg = colors.color2, bg = colors.background },
    CmpItemAbbrMatch       = { fg = colors.color7, bg = colors.background },
    CmpItemAbbrMatchFuzzy  = { fg = colors.color7, bg = colors.background },
    CmpItemKind            = { fg = colors.color4, bg = colors.background },
    CmpItemMenu            = { fg = colors.color2, bg = colors.background },

    -- treesitter
    TSNote                 = { fg = colors.background, bg = colors.color5 },
    TSWarning              = { fg = colors.background, bg = colors.color5 },
    TSDanger               = { fg = colors.background, bg = colors.color3 },
    TSTextReference        = { fg = colors.color8 },
    TSAttribute            = { fg = colors.color10, guisp = nil },
    TSBoolean              = { fg = colors.color9, guisp = nil },
    TSCharacter            = { fg = colors.color8, guisp = nil },
    TSComment              = { fg = colors.color3, gui = 'italic', guisp = nil },
    TSConstructor          = { fg = colors.color13, guisp = nil },
    TSConditional          = { fg = colors.color14, guisp = nil },
    TSConstant             = { fg = colors.color9, guisp = nil },
    TSConstBuiltin         = { fg = colors.color9, gui = 'italic', guisp = nil },
    TSConstMacro           = { fg = colors.color8, guisp = nil },
    TSError                = { fg = colors.color8, guisp = nil },
    TSException            = { fg = colors.color8, guisp = nil },
    TSField                = { fg = colors.color5, guisp = nil },
    TSFloat                = { fg = colors.color9, guisp = nil },
    TSFunction             = { fg = colors.color13, guisp = nil },
    TSFuncBuiltin          = { fg = colors.color13, gui = 'italic', guisp = nil },
    TSFuncMacro            = { fg = colors.color8, guisp = nil },
    TSInclude              = { fg = colors.color13, guisp = nil },
    TSKeyword              = { fg = colors.color14, guisp = nil },
    TSKeywordFunction      = { fg = colors.color14, guisp = nil },
    TSKeywordOperator      = { fg = colors.color14, guisp = nil },
    TSLabel                = { fg = colors.color10, guisp = nil },
    TSMethod               = { fg = colors.color13, guisp = nil },
    TSNamespace            = { fg = colors.color8, guisp = nil },
    TSNone                 = { fg = colors.color5, guisp = nil },
    TSNumber               = { fg = colors.color9, guisp = nil },
    TSOperator             = { fg = colors.color5, guisp = nil },
    TSParameter            = { fg = colors.color5, guisp = nil },
    TSParameterReference   = { fg = colors.color5, guisp = nil },
    TSProperty             = { fg = colors.color5, guisp = nil },
    TSPunctDelimiter       = { fg = colors.color15, guisp = nil },
    TSPunctBracket         = { fg = colors.color5, guisp = nil },
    TSPunctSpecial         = { fg = colors.color5, guisp = nil },
    TSRepeat               = { fg = colors.color14, guisp = nil },
    TSString               = { fg = colors.color11, guisp = nil },
    TSStringRegex          = { fg = colors.color12, guisp = nil },
    TSStringEscape         = { fg = colors.color12, guisp = nil },
    TSSymbol               = { fg = colors.color11, guisp = nil },
    TSTag                  = { fg = colors.color8, guisp = nil },
    TSTagDelimiter         = { fg = colors.color15, guisp = nil },
    TSText                 = { fg = colors.color5, guisp = nil },
    TSStrong               = { fg = nil, gui = 'bold', guisp = nil },
    TSEmphasis             = { fg = colors.color9, gui = 'italic', guisp = nil },
    TSUnderline            = { fg = colors.color0, gui = 'underline', guisp = nil },
    TSStrike               = { fg = colors.color0, gui = 'strikethrough', guisp = nil },
    TSTitle                = { fg = colors.color13, guisp = nil },
    TSLiteral              = { fg = colors.color9, guisp = nil },
    TSURI                  = { fg = colors.color9, gui = 'underline', guisp = nil },
    TSType                 = { fg = colors.color10, guisp = nil },
    TSTypeBuiltin          = { fg = colors.color10, gui = 'italic', guisp = nil },
    TSVariable             = { fg = colors.color8, guisp = nil },
    TSVariableBuiltin      = { fg = colors.color8, gui = 'italic', guisp = nil },
    TSDefinition           = { fg = nil, gui = 'underline', guisp = colors.color4 },
    TSDefinitionUsage      = { fg = nil, gui = 'underline', guisp = colors.color4 },
    TSCurrentScope         = { fg = nil, gui = 'bold', guisp = nil },


    -- LspTrouble
    LspTroubleText = { fg = colors.foreground },
    LspTroubleCount = { fg = colors.color6, bg = colors.foreground },
    LspTroubleNormal = { fg = colors.foreground, bg = colors.background },

    -- Illuminate
    illuminatedWord = { bg = colors.foreground },
    illuminatedCurWord = { bg = colors.foreground },

    -- diff
    diffAdded = { fg = colors.color4 },
    diffRemoved = { fg = colors.color11 },
    diffChanged = { fg = colors.color5 },
    diffOldFile = { fg = colors.color5 },
    diffNewFile = { fg = colors.color5 },
    diffFile = { fg = colors.color7 },
    diffLine = { fg = colors.color1 },
    diffIndexLine = { fg = colors.color6 },

    -- Neogit
    NeogitBranch = { fg = colors.color6 },
    NeogitRemote = { fg = colors.color6 },
    NeogitHunkHeader = { bg = colors.background, fg = colors.foreground },
    NeogitHunkHeaderHighlight = { bg = colors.foreground, fg = colors.color7 },
    NeogitDiffContextHighlight = { bg = colors.background, fg = colors.foreground },
    NeogitDiffDeleteHighlight = { fg = colors.color11, bg = colors.color11 },
    NeogitDiffAddHighlight = { fg = colors.color4, bg = colors.color4 },

    -- GitGutter
    GitGutterAdd = { fg = colors.color4 },     -- diff mode: Added line |diff.txt|
    GitGutterChange = { fg = colors.color5 },  -- diff mode: Changed line |diff.txt|
    GitGutterDelete = { fg = colors.color11 }, -- diff mode: Deleted line |diff.txt|

    -- GitSigns
    GitSignsAdd = { fg = colors.color4 },     -- diff mode: Added line |diff.txt|
    GitSignsChange = { fg = colors.color5 },  -- diff mode: Changed line |diff.txt|
    GitSignsDelete = { fg = colors.color11 }, -- diff mode: Deleted line |diff.txt|

    -- Telescope
    TelescopeBorder = { fg = colors.color1, bg = colors.background },
    TelescopeNormal = { fg = colors.foreground, bg = colors.background },
    TelescopeSelection = { fg = colors.background, bg = colors.color1 },

    -- Indent Blank Line
    IndentBlanklineChar = { fg = colors.color1, bg = colors.background },

    -- NvimTree
    NvimTreeNormal = { fg = colors.foreground, bg = colors.background },
    NvimTreeNormalNC = { fg = colors.foreground, bg = colors.background },
    NvimTreeRootFolder = { fg = colors.color1 },
    NvimTreeGitDirty = { fg = colors.color5 },
    NvimTreeGitNew = { fg = colors.color4 },
    NvimTreeGitDeleted = { fg = colors.color11 },
    NvimTreeSpecialFile = { fg = colors.color6 },
    NvimTreeIndentMarker = { fg = colors.foreground },
    NvimTreeImageFile = { fg = colors.foreground },
    NvimTreeSymlink = { fg = colors.color7 },
    NvimTreeFolderIcon = { fg = colors.color2, bg = colors.background },
    NvimTreeStatusLineNC = { bg = colors.background, fg = colors.background },

    -- LspSaga
    LspFloatWinNormal = { bg = colors.background },
    LspFloatWinBorder = { fg = colors.foreground },
    LspSagaBorderTitle = { fg = colors.color7 },
    LspSagaHoverBorder = { fg = colors.color7 },
    LspSagaRenameBorder = { fg = colors.color4 },
    LspSagaDefPreviewBorder = { fg = colors.color4 },
    LspSagaCodeActionBorder = { fg = colors.color7 },
    LspSagaFinderSelection = { fg = colors.color1 },
    LspSagaCodeActionTitle = { fg = colors.color7 },
    LspSagaCodeActionContent = { fg = colors.color6 },
    LspSagaSignatureHelpBorder = { fg = colors.color11 },
    ReferencesCount = { fg = colors.color6 },
    DefinitionCount = { fg = colors.color6 },
    DefinitionIcon = { fg = colors.color7 },
    ReferencesIcon = { fg = colors.color7 },
    TargetWord = { fg = colors.color7 },

    -- NeoVim
    healthError = { fg = colors.color11 },
    healthSuccess = { fg = colors.color4 },
    healthWarning = { fg = colors.color5 },

    -- BufferLine
    BufferLineIndicatorSelected = { fg = colors.color5 },
    BufferLineFill = { bg = colors.background },
  }
end

return M
