local M = {}

M.highlights_base = function(colors)
	return {
		Normal = { fg = colors.foreground, bg = colors.background },
		StatusLineNC = { bg = colors.background, fg = colors.color1 },
		StatusLine = { bg = colors.background, fg = colors.background },
		SignColumn = { bg = colors.background, fg = colors.color1 },
		MsgArea = { fg = colors.foreground, bg = colors.background },
		ModeMsg = { fg = colors.foreground, bg = colors.background },
		MsgSeparator = { fg = colors.foreground, bg = colors.background },
		SpellBad = { fg = colors.color2 },
		SpellCap = { fg = colors.color6 },
		SpellLocal = { fg = colors.color4 },
		SpellRare = { fg = colors.color6 },
		NormalNC = { fg = colors.foreground, bg = colors.background },
		Pmenu = { fg = colors.foreground, bg = colors.background },
		PmenuSel = { fg = colors.foreground, bg = colors.color1 },
		WildMenu = { fg = colors.foreground, bg = colors.color1 },
		CursorLineNr = { fg = colors.color1 },
		Comment = { fg = colors.color3 },
		Folded = { fg = colors.color4, bg = colors.background },
		FoldColumn = { fg = colors.color4, bg = colors.background },
		LineNr = { fg = colors.color9, bg = colors.background },
		FloatBorder = { fg = colors.foreground, bg = colors.background },
		Whitespace = { fg = colors.color1 },
		VertSplit = { fg = colors.background, bg = colors.color1 },
		CursorLine = { bg = colors.background },
		CursorColumn = { bg = colors.background },
		ColorColumn = { bg = colors.color1 },
		NormalFloat = { bg = colors.background },
		Visual = { bg = colors.color1, fg = colors.foreground },
		VisualNOS = { bg = colors.background },
		WarningMsg = { fg = colors.color3, bg = colors.background },
		DiffAdd = { fg = colors.foreground, bg = colors.color1 },
		DiffChange = { fg = colors.foreground, bg = colors.color2 },
		DiffDelete = { fg = colors.background, bg = colors.color7 },
		QuickFixLine = { bg = colors.color1 },
		PmenuSbar = { bg = colors.background },
		PmenuThumb = { bg = colors.color1 },
		MatchParen = { fg = colors.color4, bg = colors.background },
		Cursor = { fg = colors.foreground, bg = colors.cursor },
		lCursor = { fg = colors.foreground, bg = colors.cursor },
		CursorIM = { fg = colors.foreground, bg = colors.cursor },
		TermCursor = { fg = colors.foreground, bg = colors.cursor },
		TermCursorNC = { fg = colors.foreground, bg = colors.cursor },
		Conceal = { fg = colors.color4, bg = colors.background },
		Directory = { fg = colors.color4 },
		SpecialKey = { fg = colors.color4 },
		Title = { fg = colors.color4 },
		ErrorMsg = { fg = colors.color11, bg = colors.background },
		Search = { fg = colors.foreground, bg = colors.color1 },
		IncSearch = { fg = colors.foreground, bg = colors.color1 },
		Substitute = { fg = colors.color1, bg = colors.color6 },
		MoreMsg = { fg = colors.color5 },
		Question = { fg = colors.color5 },
		EndOfBuffer = { fg = colors.background },
		NonText = { fg = colors.color1 },
		Variable = { fg = colors.color5 },
		String = { fg = colors.color11 },
		Character = { fg = colors.color12 },
		Constant = { fg = colors.color9 },
		Number = { fg = colors.color9 },
		Boolean = { fg = colors.color9 },
		Float = { fg = colors.color9 },
		Identifier = { fg = colors.color8 },
		Function = { fg = colors.color13 },
		Operator = { fg = colors.color5 },
		Type = { fg = colors.color10 },
		StorageClass = { fg = colors.color10 },
		Structure = { fg = colors.color14 },
		Typedef = { fg = colors.color10 },
		Keyword = { fg = colors.color14 },
		Statement = { fg = colors.color8 },
		Conditional = { fg = colors.color14 },
		Repeat = { fg = colors.color10 },
		Label = { fg = colors.color10 },
		Exception = { fg = colors.color6 },
		Include = { fg = colors.color6 },
		PreProc = { fg = colors.color10 },
		Define = { fg = colors.color14 },
		Macro = { fg = colors.color6 },
		PreCondit = { fg = colors.color6 },
		Special = { fg = colors.color12 },
		SpecialChar = { fg = colors.color15 },
		Tag = { fg = colors.color10 },
		Debug = { fg = colors.color11 },
		Delimiter = { fg = colors.color15 },
		SpecialComment = { fg = colors.color2 },
		Ignore = { fg = colors.color7, bg = colors.background },
		Todo = { fg = colors.color10, bg = colors.background },
		Error = { fg = colors.color11, bg = colors.background },
		TabLine = { fg = colors.color2, bg = colors.background },
		TabLineSel = { fg = colors.foreground, bg = colors.background },
		TabLineFill = { fg = colors.foreground, bg = colors.background },
		CmpDocumentationBorder = { fg = colors.color5, bg = colors.background },
		CmpDocumentation = { fg = colors.color5, bg = colors.background },
		CmpItemAbbr = { fg = colors.foreground, bg = colors.background },
		CmpItemAbbrDeprecated = { fg = colors.color2, bg = colors.background },
		CmpItemAbbrMatch = { fg = colors.color7, bg = colors.background },
		CmpItemAbbrMatchFuzzy = { fg = colors.color7, bg = colors.background },
		CmpItemKind = { fg = colors.color4, bg = colors.background },
		CmpItemMenu = { fg = colors.color2, bg = colors.background },

		-- treesitter
		TSNote = { fg = colors.background, bg = colors.color5 },
		TSWarning = { fg = colors.background, bg = colors.color5 },
		TSDanger = { fg = colors.background, bg = colors.color3 },
		TSTextReference = { fg = colors.color8 },
		TSAttribute = { fg = colors.color10 },
		TSBoolean = { fg = colors.color9 },
		TSCharacter = { fg = colors.color8 },
		TSComment = { fg = colors.color3 },
		TSConstructor = { fg = colors.color13 },
		TSConditional = { fg = colors.color14 },
		TSConstant = { fg = colors.color9 },
		TSConstBuiltin = { fg = colors.color9 },
		TSConstMacro = { fg = colors.color8 },
		TSError = { fg = colors.color8 },
		TSException = { fg = colors.color8 },
		TSField = { fg = colors.color5 },
		TSFloat = { fg = colors.color9 },
		TSFunction = { fg = colors.color13 },
		TSFuncBuiltin = { fg = colors.color13 },
		TSFuncMacro = { fg = colors.color8 },
		TSInclude = { fg = colors.color13 },
		TSKeyword = { fg = colors.color14 },
		TSKeywordFunction = { fg = colors.color14 },
		TSKeywordOperator = { fg = colors.color14 },
		TSLabel = { fg = colors.color10 },
		TSMethod = { fg = colors.color13 },
		TSNamespace = { fg = colors.color8 },
		TSNone = { fg = colors.color5 },
		TSNumber = { fg = colors.color9 },
		TSOperator = { fg = colors.color5 },
		TSParameter = { fg = colors.color5 },
		TSParameterReference = { fg = colors.color5 },
		TSProperty = { fg = colors.color5 },
		TSPunctDelimiter = { fg = colors.color15 },
		TSPunctBracket = { fg = colors.color5 },
		TSPunctSpecial = { fg = colors.color5 },
		TSRepeat = { fg = colors.color14 },
		TSString = { fg = colors.color11 },
		TSStringRegex = { fg = colors.color12 },
		TSStringEscape = { fg = colors.color12 },
		TSSymbol = { fg = colors.color11 },
		TSTag = { fg = colors.color8 },
		TSTagDelimiter = { fg = colors.color15 },
		TSText = { fg = colors.color5 },
		TSStrong = { fg = colors.color10 },
		TSEmphasis = { fg = colors.color9 },
		TSUnderline = { fg = colors.color0 },
		TSStrike = { fg = colors.color0 },
		TSTitle = { fg = colors.color13 },
		TSLiteral = { fg = colors.color9 },
		TSURI = { fg = colors.color9 },
		TSType = { fg = colors.color10 },
		TSTypeBuiltin = { fg = colors.color10 },
		TSVariable = { fg = colors.color8 },
		TSVariableBuiltin = { fg = colors.color8 },
		TSDefinition = { fg = colors.color10 },
		TSDefinitionUsage = { fg = colors.color10 },
		TSCurrentScope = { fg = colors.color10 },

		-- LspTrouble
		LspTroubleText = { fg = colors.foreground },
		LspTroubleCount = { fg = colors.color6, bg = colors.foreground },
		LspTroubleNormal = { fg = colors.foreground, bg = colors.background },

		-- Illuminate
		illuminatedWord = { bg = colors.foreground },
		illuminatedCurWord = { bg = colors.foreground },

		-- diff
		diffAdded = { fg = colors.color4 },
		diffRemoved = { fg = colors.color11 },
		diffChanged = { fg = colors.color5 },
		diffOldFile = { fg = colors.color5 },
		diffNewFile = { fg = colors.color5 },
		diffFile = { fg = colors.color7 },
		diffLine = { fg = colors.color1 },
		diffIndexLine = { fg = colors.color6 },

		-- Neogit
		NeogitBranch = { fg = colors.color6 },
		NeogitRemote = { fg = colors.color6 },
		NeogitHunkHeader = { bg = colors.background, fg = colors.foreground },
		NeogitHunkHeaderHighlight = { bg = colors.foreground, fg = colors.color7 },
		NeogitDiffContextHighlight = { bg = colors.background, fg = colors.foreground },
		NeogitDiffDeleteHighlight = { fg = colors.color11, bg = colors.color11 },
		NeogitDiffAddHighlight = { fg = colors.color4, bg = colors.color4 },

		-- GitGutter
		GitGutterAdd = { fg = colors.color4 }, -- diff mode: Added line |diff.txt|
		GitGutterChange = { fg = colors.color5 }, -- diff mode: Changed line |diff.txt|
		GitGutterDelete = { fg = colors.color11 }, -- diff mode: Deleted line |diff.txt|

		-- GitSigns
		GitSignsAdd = { fg = colors.color4 }, -- diff mode: Added line |diff.txt|
		GitSignsChange = { fg = colors.color5 }, -- diff mode: Changed line |diff.txt|
		GitSignsDelete = { fg = colors.color11 }, -- diff mode: Deleted line |diff.txt|

		-- Telescope
		TelescopeBorder = { fg = colors.color1, bg = colors.background },
		TelescopeNormal = { fg = colors.foreground, bg = colors.background },
		TelescopeSelection = { fg = colors.foreground, bg = colors.color1 },

		-- Indent Blank Line
		IndentBlanklineChar = { fg = colors.color1, bg = colors.background },

		-- NvimTree
		NvimTreeNormal = { fg = colors.foreground, bg = colors.background },
		NvimTreeNormalNC = { fg = colors.foreground, bg = colors.background },
		NvimTreeRootFolder = { fg = colors.color1 },
		NvimTreeGitDirty = { fg = colors.color5 },
		NvimTreeGitNew = { fg = colors.color4 },
		NvimTreeGitDeleted = { fg = colors.color11 },
		NvimTreeSpecialFile = { fg = colors.color6 },
		NvimTreeIndentMarker = { fg = colors.foreground },
		NvimTreeImageFile = { fg = colors.foreground },
		NvimTreeSymlink = { fg = colors.color7 },
		NvimTreeFolderIcon = { fg = colors.color2, bg = colors.background },
		NvimTreeStatusLineNC = { bg = colors.background, fg = colors.background },

		-- LspSaga
		LspFloatWinNormal = { bg = colors.background },
		LspFloatWinBorder = { fg = colors.foreground },
		LspSagaBorderTitle = { fg = colors.color7 },
		LspSagaHoverBorder = { fg = colors.color7 },
		LspSagaRenameBorder = { fg = colors.color4 },
		LspSagaDefPreviewBorder = { fg = colors.color4 },
		LspSagaCodeActionBorder = { fg = colors.color7 },
		LspSagaFinderSelection = { fg = colors.color1 },
		LspSagaCodeActionTitle = { fg = colors.color7 },
		LspSagaCodeActionContent = { fg = colors.color6 },
		LspSagaSignatureHelpBorder = { fg = colors.color11 },
		ReferencesCount = { fg = colors.color6 },
		DefinitionCount = { fg = colors.color6 },
		DefinitionIcon = { fg = colors.color7 },
		ReferencesIcon = { fg = colors.color7 },
		TargetWord = { fg = colors.color7 },

		-- NeoVim
		healthError = { fg = colors.color11 },
		healthSuccess = { fg = colors.color4 },
		healthWarning = { fg = colors.color5 },

		-- BufferLine
		BufferLineIndicatorSelected = { fg = colors.color5 },
		BufferLineFill = { bg = colors.background },
	}
end

return M
